(source melpa)

(depends-on "cask")

(depends-on "expand-region")
(depends-on "ace-jump-mode")

(depends-on "flx-ido")
(depends-on "ido-vertical-mode")

(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "ag")

(depends-on "multiple-cursors")
(depends-on "auto-complete")
(depends-on "yasnippet")

(depends-on "emmet-mode")
(depends-on "htmlize")
(depends-on "web-mode")
(depends-on "php-mode")

(depends-on "magit")
(depends-on "fold-dwim")

(depends-on "color-theme-solarized")
