(source melpa)

(depends-on "cask")
(depends-on "color-theme-solarized")

(depends-on "expand-region")
(depends-on "ace-jump-mode")

(depends-on "ido-vertical-mode")
(depends-on "flx-ido")

(depends-on "projectile")
(depends-on "helm-projectile")

(depends-on "auto-complete")
(depends-on "yasnippet")

(depends-on "web-mode")
(depends-on "php-mode")

(depends-on "magit")
(depends-on "git-gutter")
(depends-on "org-pomodoro")

(depends-on "fold-dwim")
